-- MySQL Script generated by MySQL Workbench
-- Fri Mar 18 15:19:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`compte_bancaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`compte_bancaire` (
  `num_compte` VARCHAR(5) NOT NULL,
  `RIB` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`num_compte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`parent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`parent` (
  `CIN` VARCHAR(8) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `mot_de_passe` VARCHAR(20) NOT NULL,
  `telephone` INT(8) NOT NULL,
  `adresse` VARCHAR(50) NOT NULL,
  `code_postal` VARCHAR(4) NOT NULL,
  `compte_bancaire_num_compte` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`CIN`),
  INDEX `fk_parent_compte_bancaire1_idx` (`compte_bancaire_num_compte` ASC) VISIBLE,
  CONSTRAINT `fk_parent_compte_bancaire1`
    FOREIGN KEY (`compte_bancaire_num_compte`)
    REFERENCES `mydb`.`compte_bancaire` (`num_compte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`etude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`etude` (
  `id_etude` INT NOT NULL,
  `niveau` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_etude`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`jardin_enfant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`jardin_enfant` (
  `id_jardin` INT NOT NULL,
  `programme` LONGTEXT NOT NULL,
  `emploi` LONGTEXT NOT NULL,
  `loisirs` LONGTEXT NOT NULL,
  `enseignants` LONGTEXT NOT NULL,
  `certificats` LONGTEXT NOT NULL,
  `prix` INT NOT NULL,
  PRIMARY KEY (`id_jardin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`secretaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`secretaire` (
  `id_secretaire` INT NOT NULL,
  `nom_s` VARCHAR(10) NOT NULL,
  `prenom_s` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_secretaire`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`enfant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`enfant` (
  `num_enfant` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(10) NOT NULL,
  `prenom` VARCHAR(10) NOT NULL,
  `date_naissance` DATE NOT NULL,
  `genre` VARCHAR(10) NOT NULL,
  `parent_CIN` VARCHAR(8) NOT NULL,
  `etude_id_etude` INT NOT NULL,
  `jardin_enfant_id_jardin` INT NOT NULL,
  `secretaire_id_secretaire` INT NOT NULL,
  PRIMARY KEY (`num_enfant`),
  INDEX `fk_enfant_parent_idx` (`parent_CIN` ASC) VISIBLE,
  INDEX `fk_enfant_etude1_idx` (`etude_id_etude` ASC) VISIBLE,
  INDEX `fk_enfant_jardin_enfant1_idx` (`jardin_enfant_id_jardin` ASC) VISIBLE,
  INDEX `fk_enfant_secretaire1_idx` (`secretaire_id_secretaire` ASC) VISIBLE,
  CONSTRAINT `fk_enfant_parent`
    FOREIGN KEY (`parent_CIN`)
    REFERENCES `mydb`.`parent` (`CIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enfant_etude1`
    FOREIGN KEY (`etude_id_etude`)
    REFERENCES `mydb`.`etude` (`id_etude`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enfant_jardin_enfant1`
    FOREIGN KEY (`jardin_enfant_id_jardin`)
    REFERENCES `mydb`.`jardin_enfant` (`id_jardin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enfant_secretaire1`
    FOREIGN KEY (`secretaire_id_secretaire`)
    REFERENCES `mydb`.`secretaire` (`id_secretaire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inscrire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inscrire` (
  `jardin_enfant_id_jardin` INT NOT NULL,
  `etude_id_etude` INT NOT NULL,
  PRIMARY KEY (`jardin_enfant_id_jardin`, `etude_id_etude`),
  INDEX `fk_jardin_enfant_has_etude_etude1_idx` (`etude_id_etude` ASC) VISIBLE,
  INDEX `fk_jardin_enfant_has_etude_jardin_enfant1_idx` (`jardin_enfant_id_jardin` ASC) VISIBLE,
  CONSTRAINT `fk_jardin_enfant_has_etude_jardin_enfant1`
    FOREIGN KEY (`jardin_enfant_id_jardin`)
    REFERENCES `mydb`.`jardin_enfant` (`id_jardin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jardin_enfant_has_etude_etude1`
    FOREIGN KEY (`etude_id_etude`)
    REFERENCES `mydb`.`etude` (`id_etude`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
